#工作流的名称
name: build and deploy

#触发工作流的事件
on:
  push:
    branches: [ "master" ]

jobs:
  build-and-deploy:
    #运行在Ubuntu最新版的镜像上运行
    runs-on: ubuntu-latest

    steps:
        #检查并拉取代码
      - name: Checkout
        uses: actions/checkout@v3
        
        #设置环境为nodejs 18
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          
        #安装模块并打包项目 
      - name: Build Project
        run: |
          npm install
          npm run build
        
        #将文件上传至云服务器  
      - name: ssh-scp-deploy
        uses: marcodallasanta/ssh-scp-deploy@v1.2.0
        with:
          #本地打包后的文件目录
          local: docs/.vitepress/dist
          #上传至远程服务器的目标目录
          remote: /usr/local/nginx/html
          #远程服务器的地址
          host: ${{ REMOTE_HOST }}
          #远程服务器的用户名
          user: ${{ REMOTE_USERNAME }}
          #远程服务器的密钥（与密码二者选其一）
          key: ${{ PRIVATE_KEY }}
          #上传后执行的脚本
          post_upload: sudo nginx -s reload
